# Generated by Django 3.0.7 on 2020-06-06 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bluffgameserver', '0002_auto_20200605_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bluffgame',
            name='current_turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_turn', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bluffgame',
            name='date_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
